export const shapeConfigs = {
  rect: (id) => ({
    id,
    type: "rect",
    x: 100,
    y: 100,
    width: 100,
    height: 100,
    fill: "green",
  }),
  star: (id) => ({
    id,
    type: "star",
    x: 150,
    y: 100,
    numPoints: 5,
    innerRadius: 20,
    outerRadius: 40,
    fill: "gold",
  }),
  heart: (id) => ({
    id,
    type: "heart",
    x: 100,
    y: 100,
    width: 100,
    height: 100,
    draggable: true,
    fill: "red",
  }),
  emoji: (id) => ({
    id,
    type: "emoji",
    x: 300,
    y: 150,
    text: "😊",
    fontSize: 40,
    draggable: true,
  }),
  triangle: (id) => ({
    id,
    type: "triangle",
    points: [300, 300, 350, 250, 400, 300],
    fill: "blue",
  }),
  default: (id) => ({
    id,
    type: "circle",
    x: 150,
    y: 150,
    radius: 50,
    fill: "grey",
  }),
};
